SELECT ins.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS ins, (SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME like '%Neutered%' or SEX_UPON_OUTCOME like '%Spayed%') outs
WHERE SEX_UPON_INTAKE like '%Intact%' and ins.ANIMAL_ID = outs.ANIMAL_ID order by ins.ANIMAL_ID;


-- review
SELECT T1.ANIMAL_ID, ANIMAL_TYPE, NAME 
FROM (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%') T1,
    ANIMAL_OUTS T2
WHERE T1.ANIMAL_ID = T2.ANIMAL_ID AND SEX_UPON_OUTCOME NOT LIKE 'Intact%' ORDER BY T1.ANIMAL_ID;
