-- 코드를 입력하세요
select distinct(m.CART_ID) 
From (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Milk') m,
		(SELECT  CART_ID FROM CART_PRODUCTS WHERE NAME='Yogurt') y 
where m.CART_ID = y.CART_ID order by m.CART_ID;

-- 다시 풀기

SELECT distinct(t1.CART_ID) 
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') t1,
        (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') t2
WHERE t1.CART_ID = t2.CART_ID ORDER BY t1.CART_ID;