SELECT HACK.HACKER_ID, HACK.NAME, CHAL.C_CHAL
    FROM HACKERS HACK
    JOIN (
        SELECT HACKER_ID, COUNT(CHALLENGE_ID) AS C_CHAL
            FROM CHALLENGES
            GROUP BY HACKER_ID
    ) CHAL
    ON HACK.HACKER_ID = CHAL.HACKER_ID
    WHERE CHAL.C_CHAL NOT IN (
        SELECT A.C_CHAL
        FROM (
            SELECT HACKER_ID, COUNT(CHALLENGE_ID) AS C_CHAL
                FROM CHALLENGES
                GROUP BY HACKER_ID
        ) A
        GROUP BY A.C_CHAL
        HAVING COUNT(A.HACKER_ID) > 1 AND A.C_CHAL != (SELECT MAX(COUNT(CHALLENGE_ID)) FROM CHALLENGES GROUP BY HACKER_ID)
    )
    ORDER BY CHAL.C_CHAL DESC, HACK.HACKER_ID;
