SELECT W.ID, P.AGE, A.COIN, W.POWER
  FROM WANDS W
     , WANDS_PROPERTY P
     , (SELECT CODE, MIN(COINS_NEEDED) AS COIN, POWER
        FROM WANDS
        GROUP BY CODE, POWER) A
WHERE W.CODE = A.CODE
  AND W.POWER = A.POWER
  AND W.COINS_NEEDED = A.COIN
  AND W.CODE = P.CODE
  AND P.IS_EVIL = 0
ORDER BY W.POWER DESC, P.AGE DESC;
