SELECT CART_ID
    FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME IN 'Yogurt' GROUP BY CART_ID)
    WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME IN 'Milk' GROUP BY CART_ID)
    ORDER BY CART_ID;
